# Built-in original practice questions for TRE-4 preparation.
FACTS = {'Hindi': [('हिंदी वर्णमाला में स्वर का उदाहरण कौन-सा है?', 'अ'),
           ('‘विद्यालय’ का पर्यायवाची कौन-सा है?', 'पाठशाला'),
           ('‘दिन’ का विलोम कौन-सा है?', 'रात'),
           ('‘जल’ का पर्यायवाची कौन-सा है?', 'पानी'),
           ('‘आकाश’ का पर्यायवाची कौन-सा है?', 'नभ'),
           ('‘अंधकार’ का विलोम कौन-सा है?', 'प्रकाश'),
           ('‘सुंदर’ का विलोम कौन-सा है?', 'कुरूप'),
           ('‘लड़का’ का स्त्रीलिंग कौन-सा है?', 'लड़की'),
           ('‘नदी’ का बहुवचन कौन-सा है?', 'नदियाँ'),
           ('‘राम ने फल खाया’ में कर्ता कौन है?', 'राम'),
           ('‘मैं स्कूल जाता हूँ’ में सर्वनाम कौन-सा है?', 'मैं'),
           ('‘धीरे-धीरे’ किस प्रकार का क्रिया-विशेषण है?', 'रीतिवाचक'),
           ('‘और’ किस प्रकार का अव्यय है?', 'समुच्चयबोधक'),
           ('‘के सामने’ किस प्रकार का अव्यय है?', 'संबंधबोधक'),
           ('‘वाह!’ किस प्रकार का अव्यय है?', 'विस्मयादिबोधक'),
           ('‘गंगा’ किस प्रकार की संज्ञा है?', 'व्यक्तिवाचक'),
           ('‘ईमानदारी’ किस प्रकार की संज्ञा है?', 'भाववाचक'),
           ('‘बच्चा खेल रहा है’ में क्रिया कौन-सी है?', 'खेल रहा है'),
           ('‘नीला आकाश’ में विशेषण कौन-सा है?', 'नीला'),
           ('‘बहुत’ किसका बोध करा सकता है?', 'परिमाण/मात्रा'),
           ('‘नाक कटना’ मुहावरे का अर्थ क्या है?', 'अपमान होना'),
           ('‘आँखों का तारा’ का अर्थ क्या है?', 'बहुत प्रिय'),
           ('‘नौ दो ग्यारह होना’ का अर्थ क्या है?', 'भाग जाना'),
           ('‘एक और एक ग्यारह’ किस भाव को दर्शाता है?', 'एकता की शक्ति'),
           ('‘जैसी करनी वैसी भरनी’ का भाव क्या है?', 'कर्म का फल मिलता है'),
           ('‘जहाँ चाह वहाँ राह’ का भाव क्या है?', 'दृढ़ इच्छा से मार्ग मिलता है'),
           ('‘अल्प’ का विलोम कौन-सा है?', 'अधिक'),
           ('‘आरंभ’ का विलोम कौन-सा है?', 'अंत'),
           ('‘उन्नति’ का विलोम कौन-सा है?', 'अवनति'),
           ('‘स्वतंत्र’ का विलोम कौन-सा है?', 'परतंत्र')],
 'English': [('Choose the noun: “The teacher praised Ravi.”', 'teacher'),
             ('Choose the pronoun: “She is reading.”', 'She'),
             ('Choose the adjective: “It is a beautiful flower.”', 'beautiful'),
             ('Choose the verb: “Birds fly.”', 'fly'),
             ('Choose the adverb: “He runs quickly.”', 'quickly'),
             ('Past tense of “go” is?', 'went'),
             ('Past tense of “eat” is?', 'ate'),
             ('Plural of “child” is?', 'children'),
             ('Plural of “mouse” is?', 'mice'),
             ('Opposite of “ancient” is?', 'modern'),
             ('Opposite of “expand” is?', 'contract'),
             ('Synonym of “happy” is?', 'glad'),
             ('Synonym of “rapid” is?', 'fast'),
             ('Article before “apple” is?', 'an'),
             ('Article before “university” is?', 'a'),
             ('Correct plural of “box” is?', 'boxes'),
             ('Comparative form of “good” is?', 'better'),
             ('Superlative form of “bad” is?', 'worst'),
             ('“I have finished my work” is which tense?', 'Present Perfect'),
             ('“She was singing” is which tense?', 'Past Continuous'),
             ('“They will come” is which tense?', 'Simple Future'),
             ('Preposition in “The book is on the table” is?', 'on'),
             ('Conjunction in “Ram and Shyam came” is?', 'and'),
             ('Interjection in “Wow! What a view!” is?', 'Wow'),
             ('Question tag: “You are ready, ___?”', 'aren’t you'),
             ('Passive voice of “Ram wrote a letter” is?', 'A letter was written by Ram'),
             ('Indirect speech: He said, “I am tired.”', 'He said that he was tired.'),
             ('One who teaches is called a?', 'teacher'),
             ('One who writes poems is called a?', 'poet'),
             ('Meaning of “honest” is?', 'truthful')],
 'Mathematics': [('25 + 37 = ?', '62'),
                 ('100 − 47 = ?', '53'),
                 ('12 × 8 = ?', '96'),
                 ('144 ÷ 12 = ?', '12'),
                 ('15% of 200 = ?', '30'),
                 ('3/4 as a decimal is?', '0.75'),
                 ('0.25 as a fraction is?', '1/4'),
                 ('LCM of 6 and 8 is?', '24'),
                 ('HCF of 18 and 24 is?', '6'),
                 ('Square of 15 is?', '225'),
                 ('Cube of 5 is?', '125'),
                 ('√81 = ?', '9'),
                 ('Perimeter of a square of side 5 cm is?', '20 cm'),
                 ('Area of a rectangle 8 cm × 5 cm is?', '40 cm²'),
                 ('Area of a triangle with base 10 cm and height 6 cm is?', '30 cm²'),
                 ('Sum of angles of a triangle is?', '180°'),
                 ('A right angle equals?', '90°'),
                 ('A straight angle equals?', '180°'),
                 ('2x + 5 = 15, x = ?', '5'),
                 ('3x = 21, x = ?', '7'),
                 ('If x=4, then x²+3 = ?', '19'),
                 ('Ratio 2:3 has total parts?', '5'),
                 ('Average of 10, 20, 30 is?', '20'),
                 ('Simple interest on ₹1000 at 10% for 1 year is?', '₹100'),
                 ('Profit when CP ₹500 and SP ₹600 is?', '₹100'),
                 ('Discount on ₹1000 at 10% is?', '₹100'),
                 ('1 km equals how many metres?', '1000'),
                 ('1 metre equals how many centimetres?', '100'),
                 ('1 litre equals how many millilitres?', '1000'),
                 ('A prime number has how many positive factors?', '2')],
 'Science': [('Basic unit of life is?', 'cell'),
             ('Green pigment in plants is?', 'chlorophyll'),
             ('Gas used by plants in photosynthesis is?', 'carbon dioxide'),
             ('Gas released during photosynthesis is?', 'oxygen'),
             ('Human heart has how many chambers?', '4'),
             ('Largest organ of human body is?', 'skin'),
             ('Blood is pumped by which organ?', 'heart'),
             ('Normal human body temperature is approximately?', '37°C'),
             ('Vitamin produced with sunlight exposure is?', 'Vitamin D'),
             ('Deficiency of vitamin C causes?', 'scurvy'),
             ('Force that attracts objects toward Earth is?', 'gravity'),
             ('SI unit of force is?', 'newton'),
             ('SI unit of electric current is?', 'ampere'),
             ('Speed of light in vacuum is approximately?', '3×10⁸ m/s'),
             ('Water boils at sea level at?', '100°C'),
             ('Water freezes at?', '0°C'),
             ('pH of pure water at room temperature is about?', '7'),
             ('Sound cannot travel through?', 'vacuum'),
             ('Planet known as the Red Planet is?', 'Mars'),
             ('Earth’s natural satellite is?', 'Moon'),
             ('Largest planet in Solar System is?', 'Jupiter'),
             ('Nearest star to Earth is?', 'Sun'),
             ('Metal liquid at room temperature is?', 'mercury'),
             ('Chemical formula of water is?', 'H₂O'),
             ('Chemical formula of carbon dioxide is?', 'CO₂'),
             ('Rusting mainly affects which metal?', 'iron'),
             ('Renewable source of energy is?', 'solar energy'),
             ('Boiling changes liquid into?', 'gas'),
             ('Photosynthesis mainly occurs in which cell organelle?', 'chloroplast'),
             ('Human lungs are mainly used for?', 'gas exchange')],
 'Social Science': [('Indian Constitution came into force on?', '26 January 1950'),
                    ('Constitution was adopted on?', '26 November 1949'),
                    ('Father of the Indian Constitution is commonly called?', 'B. R. Ambedkar'),
                    ('India is a?', 'democratic republic'),
                    ('Lower House of Indian Parliament is?', 'Lok Sabha'),
                    ('Upper House of Indian Parliament is?', 'Rajya Sabha'),
                    ('Head of the Indian Union is?', 'President'),
                    ('Council of Ministers is headed by?', 'Prime Minister'),
                    ('Fundamental Rights are in which part of Constitution?', 'Part III'),
                    ('Directive Principles are in which part?', 'Part IV'),
                    ('Panchayati Raj relates to?', 'local self-government'),
                    ('India became independent in?', '1947'),
                    ('Quit India Movement was launched in?', '1942'),
                    ('Non-Cooperation Movement began in?', '1920'),
                    ('Dandi March was associated with?', 'Salt Satyagraha'),
                    ('Battle of Plassey took place in?', '1757'),
                    ('Permanent Settlement was introduced by?', 'Lord Cornwallis'),
                    ('Green Revolution is associated with?', 'increased agricultural production'),
                    ('White Revolution is associated with?', 'milk production'),
                    ('GDP stands for?', 'Gross Domestic Product'),
                    ('Agriculture belongs to which sector?', 'primary sector'),
                    ('Banking belongs to which sector?', 'tertiary sector'),
                    ('Demand and supply are concepts of?', 'economics'),
                    ('The Tropic of Cancer passes through?', 'India'),
                    ('Largest state of India by area is?', 'Rajasthan'),
                    ('Longest river in India is commonly considered?', 'Ganga'),
                    ('Capital of Bihar is?', 'Patna'),
                    ('Bihar was separated from Bengal in?', '1912'),
                    ('Bodh Gaya is associated with?', 'Gautama Buddha'),
                    ('Nalanda was famous as a?', 'ancient centre of learning')],
 'General Studies': [('Capital of India is?', 'New Delhi'),
                     ('National animal of India is?', 'Bengal tiger'),
                     ('National bird of India is?', 'Indian peacock'),
                     ('National flower of India is?', 'lotus'),
                     ('National tree of India is?', 'banyan'),
                     ('Currency of India is?', 'Indian rupee'),
                     ('Largest ocean is?', 'Pacific Ocean'),
                     ('Highest mountain above sea level is?', 'Mount Everest'),
                     ('Largest continent is?', 'Asia'),
                     ('Smallest continent is?', 'Australia'),
                     ('United Nations was founded in?', '1945'),
                     ('WHO headquarters is in?', 'Geneva'),
                     ('ISRO headquarters is in?', 'Bengaluru'),
                     ('India’s space agency is?', 'ISRO'),
                     ('RBI stands for?', 'Reserve Bank of India'),
                     ('RBI is India’s?', 'central bank'),
                     ('Indian national anthem was written by?', 'Rabindranath Tagore'),
                     ('Vande Mataram was written by?', 'Bankim Chandra Chattopadhyay'),
                     ('First President of India was?', 'Rajendra Prasad'),
                     ('First Prime Minister of India was?', 'Jawaharlal Nehru'),
                     ('National Science Day in India is observed on?', '28 February'),
                     ('Teachers’ Day in India is observed on?', '5 September'),
                     ('Children’s Day in India is observed on?', '14 November'),
                     ('World Environment Day is observed on?', '5 June'),
                     ('International Yoga Day is observed on?', '21 June'),
                     ('Bihar’s famous festival associated with the Sun is?', 'Chhath Puja'),
                     ('Madhubani painting is associated with?', 'Bihar'),
                     ('Sanjay Gandhi Biological Park is in?', 'Patna'),
                     ('Valmiki Tiger Reserve is in?', 'Bihar')],
 'Other': [('HTML stands for?', 'HyperText Markup Language'),
           ('CSS is mainly used for?', 'styling web pages'),
           ('URL stands for?', 'Uniform Resource Locator'),
           ('HTTP is a protocol used for?', 'web communication'),
           ('CPU stands for?', 'Central Processing Unit'),
           ('RAM is a type of?', 'volatile memory'),
           ('PDF stands for?', 'Portable Document Format'),
           ('CSV stands for?', 'Comma-Separated Values'),
           ('A spreadsheet cell is identified by?', 'row and column'),
           ('Keyboard shortcut for copy is?', 'Ctrl+C'),
           ('Keyboard shortcut for paste is?', 'Ctrl+V'),
           ('Keyboard shortcut for undo is?', 'Ctrl+Z'),
           ('Binary number system uses which digits?', '0 and 1'),
           ('1 byte equals?', '8 bits'),
           ('An operating system manages?', 'computer resources'),
           ('A web browser is used to?', 'access websites'),
           ('Email is used to?', 'send electronic messages'),
           ('Cloud storage means storing data?', 'on remote servers'),
           ('A strong password should generally be?', 'long and unique'),
           ('Two-factor authentication adds?', 'an additional verification step'),
           ('Phishing is an attempt to?', 'steal information through deception'),
           ('A database is used to?', 'store and organize data'),
           ('SQL is commonly used to?', 'query databases'),
           ('Git is commonly used for?', 'version control'),
           ('GitHub is commonly used to?', 'host code repositories'),
           ('Python is a?', 'programming language'),
           ('Flask is a?', 'Python web framework'),
           ('PostgreSQL is a?', 'relational database system'),
           ('Render is a platform for?', 'deploying web applications'),
           ('Supabase provides?', 'hosted database and backend services')]}
